version: "3"

services:
    peer1:
        build: ./eureka-server
        image: nizouba/eureka-server1
        ports:
            - "1111:1111"
        environment:
            - TZ=Asia/Shanghai
        command: "--spring.profiles.active=peer1"
        healthcheck:
           test: ["CMD", "curl", "-f", "http://peer2:1112"]
           interval: 10s
           timeout: 5s
           retries: 3
    peer2:
        build: ./eureka-server
        image: nizouba/eureka-server2
        ports:
            - "1112:1112"
        environment:
            - TZ=Asia/Shanghai
        command: "--spring.profiles.active=peer2"
        healthcheck:
           test: ["CMD", "curl", "-f", "http://peer1:1111"]
           interval: 10s
           timeout: 5s
           retries: 3
    hello-service1:
        build: ./hello-service
        image: nizouba/hello-service1
        ports:
            - "8081:8081"
        environment:
            - TZ=Asia/Shanghai
        command: "--server.port=8081"
        healthcheck:
           test: ["CMD-SHELL", "curl -f http://peer1:1111 || curl -f http://peer2:1112 "]
           interval: 10s
           timeout: 5s
           retries: 3
    hello-service2:
        build: ./hello-service
        image: nizouba/hello-service2
        ports:
            - "8082:8082"
        environment:
            - TZ=Asia/Shanghai
        command: "--server.port=8082"
        healthcheck:
           test: ["CMD-SHELL", "curl -f http://peer1:1111 || curl -f http://peer2:1112 "]
           interval: 10s
           timeout: 5s
           retries: 3
    ribbon-consumer:
        build: ./ribbon-consumer
        image: nizouba/ribbon-consumer
        ports:
            - "9000:9000"
        environment:
            - TZ=Asia/Shanghai
        healthcheck:
           test: ["CMD-SHELL", "curl -f http://peer1:1111 || curl -f http://peer2:1112 "]
           interval: 10s
           timeout: 5s
           retries: 3


