version: "3"

services:
    peer1:
        build: ./eureka-server
        image: nizouba/eureka-server1
        ports:
            - "1111:1111"
        environment:
            - TZ=Asia/Shanghai
        command: "--spring.profiles.active=peer1"
    peer2:
        build: ./eureka-server
        image: nizouba/eureka-server2
        ports:
            - "1112:1112"
        environment:
            - TZ=Asia/Shanghai
        command: "--spring.profiles.active=peer2"
    hello-service:
        build: ./hello-service
        image: nizouba/hello-service
        ports:
            - "8081:8081"
        environment:
            - TZ=Asia/Shanghai
        healthcheck:
           test: ["CMD", "curl", "-f", "http://peer1:1111"]
           interval: 10s
           timeout: 5s
           retries: 3

