version: "3"

services:
    eureka:
        build: ./eureka-server
        image: nizouba/eureka-server
        ports:
            - "1111:1111"
        environment:
            - TZ=Asia/Shanghai
    hello-service:
        build: ./hello-service
        image: nizouba/hello-service
        ports:
            - "8081:8081"
        environment:
            - TZ=Asia/Shanghai
        healthcheck:
           test: ["CMD", "curl", "-f", "http://eureka:1111"]
           interval: 10s
           timeout: 5s
           retries: 3
